name: main-bot

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  quality_checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci
        cd ../backend && npm ci

    - name: Check code formatting
      run: |
        npx prettier --check "**/*.{js,jsx,ts,tsx,json,md}"

    - name: Run ESLint
      run: |
        cd frontend && npm run lint
        cd ../backend && npm run lint

    - name: Run tests
      run: |
        cd frontend && npm test -- --watchAll=false
        cd ../backend && npm test

    - name: Check for security vulnerabilities
      run: |
        npm audit
        cd frontend && npm audit
        cd ../backend && npm audit

  build_check:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Build frontend
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Build backend
      run: |
        cd backend
        npm ci
        npm run build
